### ISSUE TITLE
doesn't work and instead loads continuously without stopping on Linux Mint

### ISSUE THREAD

**Issue by bobwatcherx** [SKbarbon/flet_ived#2]
my code

```python
from flet_ivid import VideoContainer # import the package
import flet


def main (page:flet.Page):
    vc = VideoContainer("myvideo.mp4", play_after_loading=True, border_radius=18, expand=True) # This is a VideoContainer
    vc.play() # call `play` function to make the video start playing.
    page.add(flet.Row([flet.Text("dqwdqwdqw")], alignment="center"))


    # Call `vc.pause()` to stop the video from playing.

flet.app(target=main)
```

error log
```
pygame 2.4.0 (SDL 2.26.4, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Please wait the video is loading..
This will take a time based on your video size...
MoviePy - Writing audio in admyvideo.mp4.mp3
MoviePy - Done.                                                                                                           
ALSA lib pcm.c:8568:(snd_pcm_recover) underrun occurred
Unhandled error processing page session : Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flet/flet.py", line 315, in on_session_created
    session_handler(page)
  File "/home/miop/belajar/fletvideo/main.py", line 9, in main
  File "/usr/local/lib/python3.10/dist-packages/flet_ivid/video_container.py", line 98, in play
    raise Exception("The control must be on page first.")
Exception: The control must be on page first.
```

**Comment by SKbarbon** [comment]
You must call vc.play() after you add the VideoContainer to the page

**Comment by SKbarbon** [comment]
@bobwatcherx hi,
You must call vc.play() after you add the VideoContainer to the page

**Comment by bobwatcherx** [comment]
yes its the same i copy you code example in github . make long time loading

Pada tanggal Sel, 23 Mei 2023 15.56, Kot ***@***.***> menulis:

**Comment by SKbarbon** [comment]
@bobwatcherx No you did not,
I can see clearly on your code that you are calling `vc.play()` before the `page.add(vc)`.

**Comment by SKbarbon** [comment]
@bobwatcherx You also did not even add the `vc` control on the page.

**Comment by SKbarbon** [comment]
> my code
> 
> 
> ```python
> 
> from flet_ivid import VideoContainer # import the package
> 
> import flet
> 
> 
> 
> 
> 
> def main (page:flet.Page):
> 
>     vc = VideoContainer("myvideo.mp4", play_after_loading=True, border_radius=18, expand=True) # This is a VideoContainer
> 
>     vc.play() # call `play` function to make the video start playing.
> 
>     page.add(flet.Row([flet.Text("dqwdqwdqw")], alignment="center"))
> 
> 
> 
> 
> 
>     # Call `vc.pause()` to stop the video from playing.
> 
> 
> 
> flet.app(target=main)
> 
> ```

# To fix
- Add the `vc` to the page.
- Use `play` function after the add.

**Comment by bobwatcherx** [comment]
yes.  it works .  but it takes long time when run flet and reload

**Comment by bobwatcherx** [comment]
first time trying to work .  but the second and subsequent ones are always like this
```
root@miop-HP-Convertible-x360-11-ab1XX:/home/miop/belajar/fletvideo# flet main.py 
pygame 2.4.0 (SDL 2.26.4, Python 3.10.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
MoviePy - Writing audio in admyvideo.mp4.mp3
MoviePy - Done.                                                                                                 
ALSA lib pcm_dmix.c:1032:(snd_pcm_dmix_open) unable to open slave
WARNING: Your device cant stream all video data and load it at the same time!, please set 'VideoContainer(play_after_loading=True)' to fix this issue.

```

**Comment by SKbarbon** [comment]
@bobwatcherx hmmm,
If you see this warning thats mean your device performance cant load the video and show it at the same time. One way to solve this issue is by wait for the video to load then show its content, To do so you need to set `play_after_loading` to True.

[About it](https://github.com/SKbarbon/flet_ived#%EF%B8%8F-if-your-device-is-old)

For example:

```python
from flet_ivid import VideoContainer # import the package
import flet


def main (page:flet.Page):
    page.bgcolor = "black"
    vc = VideoContainer("yourvideo.mp4", play_after_loading=True, border_radius=18, expand=True) # This is a VideoContainer
    page.add(flet.Row([vc], alignment="center"))

    vc.play() # call `play` function to make the video start playing.

    # Call `vc.pause()` to stop the video from playing.

flet.app(target=main)
```
